include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    cascade_invocations: false