name: flutterdex
description: "A Flutter Pokedex!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_route: ^8.0.3
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intrinsic_size_builder: ^2.0.2
  json_annotation: ^4.8.1
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  auto_route_generator: ^8.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pokeapi.sqlite3
    - assets/sprites/pokemon/
