name: flutterdex
description: "A Flutter Pokedex!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  auto_route: ^8.0.3
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intrinsic_size_builder: ^2.0.2
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  url_launcher: ^6.2.6

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  sqflite_common_ffi: ^2.3.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pokeapi.sqlite3
    - assets/sprites/pokemon/
